set shell := ["sh", "-c"]
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

#set allow-duplicate-recipe
#set positional-arguments

set dotenv-filename := ".env"
set export := true

import? "local.justfile"

build:
    bun build main.code.js --minify --outfile main.js
